### ISSUE TITLE
Cannot disable user gestures on webview

### ISSUE THREAD

**Issue by pcaffardi** [WebReflection/jsgtk#18]
Is there any way to disable zoom gestures into your webview example?

**Comment by WebReflection** [comment]
have you tried with HTML?

```html
<meta
  name="viewport"
  content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no"
>
```

**Comment by pcaffardi** [comment]
Yes, i already tried but nothing, this does not work too! :-(


Il giorno lun 1 ott 2018 alle ore 17:26 Andrea Giammarchi <
notifications@github.com> ha scritto:

**Comment by WebReflection** [comment]
Just to clarify, this is **not** a bug, which is why I've closed the issue. It's eventually in WebKitGTK that you should try to find out if there is a way to force a scale.

There is a method, but I haven't tried myself:
https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#webkit-web-view-set-zoom-level
